
--J:\SYBASE\OracleSolutions\Oracle\GAO\dbsecscan_account_maintain\dbsecscan scripts
--DBSECSCAN SCRIPT##

CREATE PROFILE GSS_PROFILE LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  CONNECT_TIME UNLIMITED
  IDLE_TIME 2880
  LOGICAL_READS_PER_SESSION UNLIMITED                                                              
  LOGICAL_READS_PER_CALL UNLIMITED
  COMPOSITE_LIMIT UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS 3
  PASSWORD_LIFE_TIME 365
  PASSWORD_REUSE_TIME 1
  PASSWORD_REUSE_MAX 3
  PASSWORD_LOCK_TIME UNLIMITED
  PASSWORD_GRACE_TIME 7
  PASSWORD_VERIFY_FUNCTION ORA12C_STRONG_VERIFY_FUNCTION;
-------------------------------------------------------------


CREATE ROLE ASSESSMENT_ROLE NOT IDENTIFIED;


CREATE ROLE GDENT NOT IDENTIFIED;
GRANT SELECT ON SYS.DBA_COL_PRIVS TO GDENT;
GRANT SELECT ON SYS.DBA_OBJECTS TO GDENT;
GRANT SELECT ON SYS.DBA_ROLES TO GDENT;
GRANT SELECT ON SYS.DBA_ROLE_PRIVS TO GDENT;
GRANT SELECT ON SYS.DBA_SYS_PRIVS TO GDENT;
GRANT SELECT ON SYS.DBA_TAB_PRIVS TO GDENT;
GRANT SELECT ON SYS.DBA_USERS TO GDENT;
GRANT SELECT ON SYS.OBJ$ TO GDENT;
GRANT SELECT ON SYS.OBJAUTH$ TO GDENT;
GRANT SELECT ON SYS.TABLE_PRIVILEGE_MAP TO GDENT;
GRANT SELECT ON SYS.USER$ TO GDENT;
GRANT SELECT ON SYS.V_$PWFILE_USERS TO GDENT;
GRANT SELECT ON SYSTEM.SQLPLUS_PRODUCT_PROFILE TO GDENT;

CREATE ROLE GDMMONITOR NOT IDENTIFIED;
GRANT SELECT ON SYS.DBA_TAB_PRIVS TO GDMMONITOR;
GRANT SELECT ON SYSTEM.SQLPLUS_PRODUCT_PROFILE TO GDMMONITOR;

CREATE ROLE OEM_MONITOR NOT IDENTIFIED;

GRANT EXECUTE ON DBSNMP.BSLN TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.BSLN_BASELINES TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.BSLN_INTERNAL TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.BSLN_METRIC_DEFAULTS TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.BSLN_METRIC_SET TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.BSLN_METRIC_T TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.BSLN_OBSERVATION_SET TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.BSLN_OBSERVATION_T TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.BSLN_STATISTICS TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.BSLN_STATISTICS_SET TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.BSLN_STATISTICS_T TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.BSLN_THRESHOLD_PARAMS TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.BSLN_TIMEGROUPS TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.BSLN_VARIANCE_SET TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.BSLN_VARIANCE_T TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_BASELINE TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_BASELINE_SQL TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_BSLN_BASELINES TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_BSLN_DATASOURCES TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_BSLN_INTERVALS TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_BSLN_METRICS TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_BSLN_STATISTICS TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_BSLN_THRESHOLD_PARMS TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_HISTORY TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_HISTORY_SQL TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_LATEST TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_LATEST_SQL TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.MGMT_RESPONSE TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.MGMT_UPDATE_DB_FEATURE_LOG TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_AQ TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_AQADM TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_DRS TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_MONITOR TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_SERVER_ALERT TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_SYSTEM TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO OEM_MONITOR;

-- System privileges granted to OEM_MONITOR
GRANT ADVISOR TO OEM_MONITOR;
GRANT ANALYZE ANY TO OEM_MONITOR;
GRANT ANALYZE ANY DICTIONARY TO OEM_MONITOR;
GRANT CREATE JOB TO OEM_MONITOR;
GRANT CREATE SESSION TO OEM_MONITOR;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'OEM_MONITOR',
  ADMIN_OPTION => FALSE);
END;
/
GRANT SELECT ANY DICTIONARY TO OEM_MONITOR;

-- Roles granted to OEM_MONITOR

GRANT SELECT_CATALOG_ROLE TO OEM_MONITOR;


GRANT OEM_MONITOR TO GDMMONITOR;

-----------------------------
CREATE USER DBSECSCAN
  IDENTIFIED BY DBsecscan##12
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE GSS_PROFILE
  ACCOUNT UNLOCK;

GRANT ASSESSMENT_ROLE TO DBSECSCAN;
GRANT DBA TO DBSECSCAN;
GRANT GDENT TO DBSECSCAN;
GRANT GDMMONITOR TO DBSECSCAN;
ALTER USER DBSECSCAN DEFAULT ROLE ALL;
  
GRANT UNLIMITED TABLESPACE TO DBSECSCAN;
